os: osx
osx_image: xcode9.3
language: swift
script: xcodebuild clean build test -project App/ChatApp.xcodeproj  -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO